name: TreeChopper
version: 1.0.1
main: pl.hansg.treechopper.TreeChopperPlugin
api-version: '26.1.2'
author: HansG
description: Simple tree chopper with leaf removal and tool durability.

commands:
  treechopper:
    description: SimpleTreeChopper command
    usage: /treechopper <toggle|reload|status>
    aliases: [tc, treechop, choptree]

permissions:
  treechopper.use:
    description: Allows player to use tree chopping
    default: true

  treechopper.toggle:
    description: Allows player to toggle tree chopping
    default: true

  treechopper.reload:
    description: Allows reloading the config
    default: op